/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IqTestRouteImport } from './routes/iq-test'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuraMarketRouteImport } from './routes/aura-market'
import { Route as AuraRouteImport } from './routes/aura'
import { Route as AssessmentChildRouteImport } from './routes/assessment-child'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AbbiRouteImport } from './routes/abbi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuraStoreRouteImport } from './routes/aura.store'
import { Route as AuraGrowthRouteImport } from './routes/aura.growth'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IqTestRoute = IqTestRouteImport.update({
  id: '/iq-test',
  path: '/iq-test',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraMarketRoute = AuraMarketRouteImport.update({
  id: '/aura-market',
  path: '/aura-market',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraRoute = AuraRouteImport.update({
  id: '/aura',
  path: '/aura',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentChildRoute = AssessmentChildRouteImport.update({
  id: '/assessment-child',
  path: '/assessment-child',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AbbiRoute = AbbiRouteImport.update({
  id: '/abbi',
  path: '/abbi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraStoreRoute = AuraStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuraRoute,
} as any)
const AuraGrowthRoute = AuraGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AuraRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abbi': typeof AbbiRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-child': typeof AssessmentChildRoute
  '/aura': typeof AuraRouteWithChildren
  '/aura-market': typeof AuraMarketRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/iq-test': typeof IqTestRoute
  '/pricing': typeof PricingRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aura/growth': typeof AuraGrowthRoute
  '/aura/store': typeof AuraStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abbi': typeof AbbiRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-child': typeof AssessmentChildRoute
  '/aura': typeof AuraRouteWithChildren
  '/aura-market': typeof AuraMarketRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/iq-test': typeof IqTestRoute
  '/pricing': typeof PricingRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aura/growth': typeof AuraGrowthRoute
  '/aura/store': typeof AuraStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abbi': typeof AbbiRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-child': typeof AssessmentChildRoute
  '/aura': typeof AuraRouteWithChildren
  '/aura-market': typeof AuraMarketRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/iq-test': typeof IqTestRoute
  '/pricing': typeof PricingRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aura/growth': typeof AuraGrowthRoute
  '/aura/store': typeof AuraStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abbi'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/assessment-child'
    | '/aura'
    | '/aura-market'
    | '/auth'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/iq-test'
    | '/pricing'
    | '/results'
    | '/roadmap'
    | '/sitemap.xml'
    | '/aura/growth'
    | '/aura/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abbi'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/assessment-child'
    | '/aura'
    | '/aura-market'
    | '/auth'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/iq-test'
    | '/pricing'
    | '/results'
    | '/roadmap'
    | '/sitemap.xml'
    | '/aura/growth'
    | '/aura/store'
  id:
    | '__root__'
    | '/'
    | '/abbi'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/assessment-child'
    | '/aura'
    | '/aura-market'
    | '/auth'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/iq-test'
    | '/pricing'
    | '/results'
    | '/roadmap'
    | '/sitemap.xml'
    | '/aura/growth'
    | '/aura/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbbiRoute: typeof AbbiRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AssessmentRoute: typeof AssessmentRoute
  AssessmentChildRoute: typeof AssessmentChildRoute
  AuraRoute: typeof AuraRouteWithChildren
  AuraMarketRoute: typeof AuraMarketRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  IqTestRoute: typeof IqTestRoute
  PricingRoute: typeof PricingRoute
  ResultsRoute: typeof ResultsRoute
  RoadmapRoute: typeof RoadmapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iq-test': {
      id: '/iq-test'
      path: '/iq-test'
      fullPath: '/iq-test'
      preLoaderRoute: typeof IqTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura-market': {
      id: '/aura-market'
      path: '/aura-market'
      fullPath: '/aura-market'
      preLoaderRoute: typeof AuraMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura': {
      id: '/aura'
      path: '/aura'
      fullPath: '/aura'
      preLoaderRoute: typeof AuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment-child': {
      id: '/assessment-child'
      path: '/assessment-child'
      fullPath: '/assessment-child'
      preLoaderRoute: typeof AssessmentChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abbi': {
      id: '/abbi'
      path: '/abbi'
      fullPath: '/abbi'
      preLoaderRoute: typeof AbbiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura/store': {
      id: '/aura/store'
      path: '/store'
      fullPath: '/aura/store'
      preLoaderRoute: typeof AuraStoreRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/growth': {
      id: '/aura/growth'
      path: '/growth'
      fullPath: '/aura/growth'
      preLoaderRoute: typeof AuraGrowthRouteImport
      parentRoute: typeof AuraRoute
    }
  }
}

interface AuraRouteChildren {
  AuraGrowthRoute: typeof AuraGrowthRoute
  AuraStoreRoute: typeof AuraStoreRoute
}

const AuraRouteChildren: AuraRouteChildren = {
  AuraGrowthRoute: AuraGrowthRoute,
  AuraStoreRoute: AuraStoreRoute,
}

const AuraRouteWithChildren = AuraRoute._addFileChildren(AuraRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbbiRoute: AbbiRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AssessmentRoute: AssessmentRoute,
  AssessmentChildRoute: AssessmentChildRoute,
  AuraRoute: AuraRouteWithChildren,
  AuraMarketRoute: AuraMarketRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  IqTestRoute: IqTestRoute,
  PricingRoute: PricingRoute,
  ResultsRoute: ResultsRoute,
  RoadmapRoute: RoadmapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
