/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as ForSchoolsRouteImport } from './routes/for-schools'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CareerResultsRouteImport } from './routes/career-results'
import { Route as CareerBattlesRouteImport } from './routes/career-battles'
import { Route as CareerAssessmentRouteImport } from './routes/career-assessment'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuraMarketRouteImport } from './routes/aura-market'
import { Route as AuraRouteImport } from './routes/aura'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AbbiRouteImport } from './routes/abbi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchoolReportRouteImport } from './routes/school.report'
import { Route as SchoolRegisterRouteImport } from './routes/school.register'
import { Route as SchoolJoinRouteImport } from './routes/school.join'
import { Route as SchoolDashboardRouteImport } from './routes/school.dashboard'
import { Route as SchoolClassBuilderRouteImport } from './routes/school.class-builder'
import { Route as SchoolAnalyticsRouteImport } from './routes/school.analytics'
import { Route as AuraStoreRouteImport } from './routes/aura.store'
import { Route as AuraGrowthRouteImport } from './routes/aura.growth'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSchoolsRoute = ForSchoolsRouteImport.update({
  id: '/for-schools',
  path: '/for-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerResultsRoute = CareerResultsRouteImport.update({
  id: '/career-results',
  path: '/career-results',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerBattlesRoute = CareerBattlesRouteImport.update({
  id: '/career-battles',
  path: '/career-battles',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerAssessmentRoute = CareerAssessmentRouteImport.update({
  id: '/career-assessment',
  path: '/career-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraMarketRoute = AuraMarketRouteImport.update({
  id: '/aura-market',
  path: '/aura-market',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraRoute = AuraRouteImport.update({
  id: '/aura',
  path: '/aura',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AbbiRoute = AbbiRouteImport.update({
  id: '/abbi',
  path: '/abbi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolReportRoute = SchoolReportRouteImport.update({
  id: '/school/report',
  path: '/school/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRegisterRoute = SchoolRegisterRouteImport.update({
  id: '/school/register',
  path: '/school/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolJoinRoute = SchoolJoinRouteImport.update({
  id: '/school/join',
  path: '/school/join',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolDashboardRoute = SchoolDashboardRouteImport.update({
  id: '/school/dashboard',
  path: '/school/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolClassBuilderRoute = SchoolClassBuilderRouteImport.update({
  id: '/school/class-builder',
  path: '/school/class-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolAnalyticsRoute = SchoolAnalyticsRouteImport.update({
  id: '/school/analytics',
  path: '/school/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraStoreRoute = AuraStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuraRoute,
} as any)
const AuraGrowthRoute = AuraGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AuraRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abbi': typeof AbbiRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/aura': typeof AuraRouteWithChildren
  '/aura-market': typeof AuraMarketRoute
  '/auth': typeof AuthRoute
  '/career-assessment': typeof CareerAssessmentRoute
  '/career-battles': typeof CareerBattlesRoute
  '/career-results': typeof CareerResultsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/for-schools': typeof ForSchoolsRoute
  '/mentors': typeof MentorsRoute
  '/pricing': typeof PricingRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
  '/aura/growth': typeof AuraGrowthRoute
  '/aura/store': typeof AuraStoreRoute
  '/school/analytics': typeof SchoolAnalyticsRoute
  '/school/class-builder': typeof SchoolClassBuilderRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/join': typeof SchoolJoinRoute
  '/school/register': typeof SchoolRegisterRoute
  '/school/report': typeof SchoolReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abbi': typeof AbbiRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/aura': typeof AuraRouteWithChildren
  '/aura-market': typeof AuraMarketRoute
  '/auth': typeof AuthRoute
  '/career-assessment': typeof CareerAssessmentRoute
  '/career-battles': typeof CareerBattlesRoute
  '/career-results': typeof CareerResultsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/for-schools': typeof ForSchoolsRoute
  '/mentors': typeof MentorsRoute
  '/pricing': typeof PricingRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
  '/aura/growth': typeof AuraGrowthRoute
  '/aura/store': typeof AuraStoreRoute
  '/school/analytics': typeof SchoolAnalyticsRoute
  '/school/class-builder': typeof SchoolClassBuilderRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/join': typeof SchoolJoinRoute
  '/school/register': typeof SchoolRegisterRoute
  '/school/report': typeof SchoolReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abbi': typeof AbbiRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/aura': typeof AuraRouteWithChildren
  '/aura-market': typeof AuraMarketRoute
  '/auth': typeof AuthRoute
  '/career-assessment': typeof CareerAssessmentRoute
  '/career-battles': typeof CareerBattlesRoute
  '/career-results': typeof CareerResultsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/for-schools': typeof ForSchoolsRoute
  '/mentors': typeof MentorsRoute
  '/pricing': typeof PricingRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
  '/aura/growth': typeof AuraGrowthRoute
  '/aura/store': typeof AuraStoreRoute
  '/school/analytics': typeof SchoolAnalyticsRoute
  '/school/class-builder': typeof SchoolClassBuilderRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/join': typeof SchoolJoinRoute
  '/school/register': typeof SchoolRegisterRoute
  '/school/report': typeof SchoolReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abbi'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/aura'
    | '/aura-market'
    | '/auth'
    | '/career-assessment'
    | '/career-battles'
    | '/career-results'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/for-schools'
    | '/mentors'
    | '/pricing'
    | '/results'
    | '/roadmap'
    | '/sitemap.xml'
    | '/success-stories'
    | '/universities'
    | '/aura/growth'
    | '/aura/store'
    | '/school/analytics'
    | '/school/class-builder'
    | '/school/dashboard'
    | '/school/join'
    | '/school/register'
    | '/school/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abbi'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/aura'
    | '/aura-market'
    | '/auth'
    | '/career-assessment'
    | '/career-battles'
    | '/career-results'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/for-schools'
    | '/mentors'
    | '/pricing'
    | '/results'
    | '/roadmap'
    | '/sitemap.xml'
    | '/success-stories'
    | '/universities'
    | '/aura/growth'
    | '/aura/store'
    | '/school/analytics'
    | '/school/class-builder'
    | '/school/dashboard'
    | '/school/join'
    | '/school/register'
    | '/school/report'
  id:
    | '__root__'
    | '/'
    | '/abbi'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/aura'
    | '/aura-market'
    | '/auth'
    | '/career-assessment'
    | '/career-battles'
    | '/career-results'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/for-schools'
    | '/mentors'
    | '/pricing'
    | '/results'
    | '/roadmap'
    | '/sitemap.xml'
    | '/success-stories'
    | '/universities'
    | '/aura/growth'
    | '/aura/store'
    | '/school/analytics'
    | '/school/class-builder'
    | '/school/dashboard'
    | '/school/join'
    | '/school/register'
    | '/school/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbbiRoute: typeof AbbiRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AssessmentRoute: typeof AssessmentRoute
  AuraRoute: typeof AuraRouteWithChildren
  AuraMarketRoute: typeof AuraMarketRoute
  AuthRoute: typeof AuthRoute
  CareerAssessmentRoute: typeof CareerAssessmentRoute
  CareerBattlesRoute: typeof CareerBattlesRoute
  CareerResultsRoute: typeof CareerResultsRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  ForSchoolsRoute: typeof ForSchoolsRoute
  MentorsRoute: typeof MentorsRoute
  PricingRoute: typeof PricingRoute
  ResultsRoute: typeof ResultsRoute
  RoadmapRoute: typeof RoadmapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  UniversitiesRoute: typeof UniversitiesRoute
  SchoolAnalyticsRoute: typeof SchoolAnalyticsRoute
  SchoolClassBuilderRoute: typeof SchoolClassBuilderRoute
  SchoolDashboardRoute: typeof SchoolDashboardRoute
  SchoolJoinRoute: typeof SchoolJoinRoute
  SchoolRegisterRoute: typeof SchoolRegisterRoute
  SchoolReportRoute: typeof SchoolReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-schools': {
      id: '/for-schools'
      path: '/for-schools'
      fullPath: '/for-schools'
      preLoaderRoute: typeof ForSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-results': {
      id: '/career-results'
      path: '/career-results'
      fullPath: '/career-results'
      preLoaderRoute: typeof CareerResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-battles': {
      id: '/career-battles'
      path: '/career-battles'
      fullPath: '/career-battles'
      preLoaderRoute: typeof CareerBattlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-assessment': {
      id: '/career-assessment'
      path: '/career-assessment'
      fullPath: '/career-assessment'
      preLoaderRoute: typeof CareerAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura-market': {
      id: '/aura-market'
      path: '/aura-market'
      fullPath: '/aura-market'
      preLoaderRoute: typeof AuraMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura': {
      id: '/aura'
      path: '/aura'
      fullPath: '/aura'
      preLoaderRoute: typeof AuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abbi': {
      id: '/abbi'
      path: '/abbi'
      fullPath: '/abbi'
      preLoaderRoute: typeof AbbiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/report': {
      id: '/school/report'
      path: '/school/report'
      fullPath: '/school/report'
      preLoaderRoute: typeof SchoolReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/register': {
      id: '/school/register'
      path: '/school/register'
      fullPath: '/school/register'
      preLoaderRoute: typeof SchoolRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/join': {
      id: '/school/join'
      path: '/school/join'
      fullPath: '/school/join'
      preLoaderRoute: typeof SchoolJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/dashboard': {
      id: '/school/dashboard'
      path: '/school/dashboard'
      fullPath: '/school/dashboard'
      preLoaderRoute: typeof SchoolDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/class-builder': {
      id: '/school/class-builder'
      path: '/school/class-builder'
      fullPath: '/school/class-builder'
      preLoaderRoute: typeof SchoolClassBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/analytics': {
      id: '/school/analytics'
      path: '/school/analytics'
      fullPath: '/school/analytics'
      preLoaderRoute: typeof SchoolAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura/store': {
      id: '/aura/store'
      path: '/store'
      fullPath: '/aura/store'
      preLoaderRoute: typeof AuraStoreRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/growth': {
      id: '/aura/growth'
      path: '/growth'
      fullPath: '/aura/growth'
      preLoaderRoute: typeof AuraGrowthRouteImport
      parentRoute: typeof AuraRoute
    }
  }
}

interface AuraRouteChildren {
  AuraGrowthRoute: typeof AuraGrowthRoute
  AuraStoreRoute: typeof AuraStoreRoute
}

const AuraRouteChildren: AuraRouteChildren = {
  AuraGrowthRoute: AuraGrowthRoute,
  AuraStoreRoute: AuraStoreRoute,
}

const AuraRouteWithChildren = AuraRoute._addFileChildren(AuraRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbbiRoute: AbbiRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AssessmentRoute: AssessmentRoute,
  AuraRoute: AuraRouteWithChildren,
  AuraMarketRoute: AuraMarketRoute,
  AuthRoute: AuthRoute,
  CareerAssessmentRoute: CareerAssessmentRoute,
  CareerBattlesRoute: CareerBattlesRoute,
  CareerResultsRoute: CareerResultsRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  ForSchoolsRoute: ForSchoolsRoute,
  MentorsRoute: MentorsRoute,
  PricingRoute: PricingRoute,
  ResultsRoute: ResultsRoute,
  RoadmapRoute: RoadmapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  UniversitiesRoute: UniversitiesRoute,
  SchoolAnalyticsRoute: SchoolAnalyticsRoute,
  SchoolClassBuilderRoute: SchoolClassBuilderRoute,
  SchoolDashboardRoute: SchoolDashboardRoute,
  SchoolJoinRoute: SchoolJoinRoute,
  SchoolRegisterRoute: SchoolRegisterRoute,
  SchoolReportRoute: SchoolReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
